# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f70c00bf80b52b00a5c78b0444f20c8e2d8aa0667f6a7935419294714832a96e31ea425f7c1a7501322d69c36fe2a3ce7024b5b6f98eb94f0a74ca0f0927fd8d

test:
  secret_key_base: 18f2fdc7fc0e70a19fbe695b6178618ce311a853c898ff301b041ce357c8d4b92151ffd6aa5e50ed9d27b88268a7208c7ad306088c48020cc38ed4df7fdb6be4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
